name: Auto-Resolve Merge Conflicts (PRs)

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  auto-resolve:
    if: github.event.pull_request.mergeable == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout base branch
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git checkout ${{ github.base_ref }}

      - name: Merge PR branch into base with "ours" strategy
        run: |
          git merge -X ours ${{ github.head_ref }} || true

      - name: Push resolved merge back to PR branch
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout ${{ github.head_ref }}
          git merge ${{ github.base_ref }}
          git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps & run tests
        run: |
          pip install -r requirements.txt
          pytest -q
